CREATE TABLE LOCATION
(
  LOCATION_ID       NUMBER(20)                        NOT NULL,  
  LOCATION_NAME       VARCHAR2(100 BYTE)                 NOT NULL,
  LOCATION_SHORT_NAME  VARCHAR2(10 BYTE)
);


CREATE UNIQUE INDEX PK_LOCATION ON LOCATION
(LOCATION_ID);

ALTER TABLE LOCATION ADD (
  CONSTRAINT PK_LOCATION
  PRIMARY KEY
  (LOCATION_ID)
  USING INDEX PK_LOCATION
  ENABLE VALIDATE);





