DROP TABLE TAX;

CREATE TABLE TAX
(
  TAX_ID                      NUMBER(20)        NOT NULL,
  TAX_NAME                      VARCHAR2(90 BYTE) NOT NULL,  
  TAX_SHORT_NAME                 VARCHAR2(15 BYTE),
  TAX_ACTIVE_DATE                 DATE              NOT NULL,
  TAX_INACTIVE_DATE                  DATE              DEFAULT TO_DATE('12/31/4712', 'MM/DD/YYYY') NOT NULL,
  TAX_LOCATION_ID                   NUMBER(20)        NOT NULL  
);

CREATE UNIQUE INDEX PK_TAX ON TAX
(TAX_ID);


ALTER TABLE TAX ADD (
 CONSTRAINT PK_TAX
  PRIMARY KEY
  (TAX_ID)
  USING INDEX PK_TAX
  ENABLE VALIDATE);


ALTER TABLE TAX ADD (
  CONSTRAINT FK_TAX_LOCATION 
  FOREIGN KEY (TAX_LOCATION_ID) 
  REFERENCES LOCATION (LOCATION_ID)
  DEFERRABLE INITIALLY IMMEDIATE
  ENABLE VALIDATE)
; 
