CREATE TABLE TAX_RATE
(
  TR_ID                       NUMBER(20)      NOT NULL,
  TR_TAX_ID                    NUMBER(20)      NOT NULL,
  TR_RATE_PERCENT                  NUMBER(9,5)
);

CREATE UNIQUE INDEX PK_TAX_RATE ON TAX_RATE
(TR_ID);

ALTER TABLE TAX_RATE ADD (
 CONSTRAINT PK_TAX_RATE
  PRIMARY KEY
  (TR_ID)
  USING INDEX PK_TAX_RATE
  ENABLE VALIDATE);


ALTER TABLE TAX_RATE ADD (
  CONSTRAINT FK_TAX 
  FOREIGN KEY (TR_TAX_ID) 
  REFERENCES TAX (TAX_ID)
  DEFERRABLE INITIALLY IMMEDIATE
  ENABLE VALIDATE)
;